### ISSUE TITLE
CORS error in web browser

### ISSUE THREAD

**Issue by foobarbecue** [toofusan/Twity#1]
twitter-for-unity is working great when I compile for Windows, but when I compile for webgl and run in a browser I get this:

> Failed to load https://stream.twitter.com/1.1/statuses/filter.json: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access. The response had HTTP status code 400.

I read around and it sounds it may be impossible to make it work due to Twitter API policy -- they don't support CORS headers. I figure I'd post an issue anyway to see if anyone has found a way to do it.

**Comment by toofusan** [comment]
@foobarbecue 
Thanks for your feedback, but I'm afraid I don't have any idea about this problem...
Does this help you...?
[Twitter CORS proxy server](https://github.com/slaypni/Corset)

**Comment by foobarbecue** [comment]
Haven't tried it yet, but I imagine something like that would work. Closing this because it's more a problem with Twitter than Twity.
