### ISSUE TITLE
Calling Get() with trends/place reponds with error

### ISSUE THREAD

**Issue by Esildor** [toofusan/Twity#15]
Kinda new to Twitter APIs, this call seems straightforward enough for a response I get:

> {"errors":[{"code":34,"message":"Sorry, that page does not exist."}]}

Heres the API docs.
https://developer.twitter.com/en/docs/trends/trends-for-location/api-reference/get-trends-place

Heres the calling code:
`Twity.Oauth.consumerKey = "blah";
        Twity.Oauth.consumerSecret = "blah";
        StartCoroutine(Twity.Client.Get("trends/place", trendsParameters, TrendsCallback));`

Note: trendsParameters is serialized in the inspector with a key: id and value: 2347598

**Comment by toofusan** [comment]
@Esildor 
I've check that endpoint, but I think Twity has no problem.

```c#
void Start () {
	Twity.Oauth.consumerKey = "hoge";
	Twity.Oauth.consumerSecret = "fuga";

	Dictionary<string, string> p = new Dictionary<string, string>();
	p["id"] = "1118370"; // http://woeid.rosselliot.co.nz/lookup/tokyo
	StartCoroutine(Twity.Client.Get("trends/place", p, TrendsPlaceCallback));
}
	
private void TrendsPlaceCallback(bool success, string response) {
	if (!success) return;
	Debug.Log(response); // => {"items":[{"trends":[{"name":"\u30A4\u30D9\u30F3\u30C8","url":"http:\/\/twitter.com\/search?q=%E3%82%A4%E3%83%99%E3%83%B3%E3%83%88", ...
}
```

But I get error response via id=2347598, so I think this WOEID 2347598 is not correct. Would you check WOEID?
