### ISSUE TITLE
[Feature Request] Generate Request Token

### ISSUE THREAD

**Issue by Barryrowe** [toofusan/Twity#2]
This library appears to work great if you already have an accessToken, but the requests needed to generate an access token have their own challenges, and would be great additions to this library.

**Comment by toofusan** [comment]
Sorry for late response.
I had realized this issue, and I think I should deal it. But with my poor skills, it will takes a bit longer X(
Please wait a while...

**Comment by Barryrowe** [comment]
No worries.

Once we get through the next milestone of our current project, I plan to try and commit back to this repo the work I did to add access token generation. That is at least a month away for us though, so if you'd like to inspect the work we've done here:

https://github.com/RoaringCatGames/ludumdare-40/blob/post-jam/Assets/Scripts/TwitterIntegration/CustomImplementation/TwitterClient.cs

It could come into this project pretty smoothly I think. There are a few more dependencies on the Twitterizer methods.

**Comment by gohugo** [comment]
Can we still do our thing with  our default Acces token that we get in the twitter App management website ?

**Comment by toofusan** [comment]
[update] Now you can use oauth2/token endpoint, and get bearer_token. Please see README.

But generating request_token is not yet...

**Comment by toofusan** [comment]
#18 
[update] update for generating request_token
POST oauth/access_token is not yet.
