### ISSUE TITLE
Bug with 3-legged oauth

### ISSUE THREAD

**Issue by Markemp** [toofusan/Twity#22]
I think I found a bug in the TwitterOauth.cs file.  I was having problems using PIN authentication.  Got the request tokens, but was getting a "Reverse auth credentials are invalid" 401 error when getting the access tokens.  Found out that the GenerateSignature() method in TwitterOauth.cs sets the tokens based on access token first (or lack thereof), then checks for the request token. 

Original code, starting around line 50:
```
if (!string.IsNullOrEmpty(accessToken)) 
{
               oauth_token = accessToken;
                oauth_token_secret = accessTokenSecret;
}
else if (!string.IsNullOrEmpty(requestToken))
{
                oauth_token = requestToken;
                oauth_token_secret = requestTokenSecret;
}
```

Fixed code:
```
if (!string.IsNullOrEmpty(requestToken))
{
	oauth_token = requestToken;
	oauth_token_secret = requestTokenSecret;
}
else if (!string.IsNullOrEmpty(accessToken))
{
	oauth_token = accessToken;
	oauth_token_secret = accessTokenSecret;
}
```

I'm still testing this, but just an FYI in case you've noticed some weird behaviors similar to this bug.  I'm not sure how this will behave if a second request token request is made (will probably fail due to the values already existing), so more refactoring may be necessary.

**Comment by Markemp** [comment]
Upon further testing, I also had to clear out the requestToken and requestTokenSecret in TwitterRequest.cs once the access tokens were successfully returned.  I added these two lines right after screenName = d["screen_name"]:

```
Oauth.requestToken = string.Empty;
Oauth.requestTokenSecret = string.Empty;
```

That makes sure that the next time a request is posted, it's using the proper access tokens.

**Comment by toofusan** [comment]
@Markemp 
I'm sorry for late reply. Thanks lot for making issue.
I'll check about an order of request_token/access_token,  and deleting request_token after getting access_token. 

FYI.
In developing my app, I also have a problem with 2 requests to generate request_token in a row. I added these 2 lines before `GenerateRequestToken()` in my app, so I should add them in this method.

```
Oauth.requestToken = string.Empty;
Oauth.requestTokenSecret = string.Empty;
```

**Comment by toofusan** [comment]
@Markemp 
I made change for this issue. I think it works properly.(I didn't change the order of oauth_token checking in TwitterOauth.cs)
