### ISSUE TITLE
tweet.user.profile_text_color always returns "333333"

### ISSUE THREAD

**Issue by TagliatL** [toofusan/Twity#6]
Hi, I'm using Twity.TweetObjectWithUser to get informations about a tweet and its user.
I get the proper profil pic, the name and every information I need on the tweet but the user.profile_text_color always returns the value 333333 when it should change depending on the user.

**Comment by toofusan** [comment]
I'm so sorry for late...
I've checked this issue, but in my environment, tweet.user.profile_text_color is different for each user.
(now I'm using Unity 2018.1.0)
Is this issue lasting in your environment?
