### ISSUE TITLE
documentation site does not work

### ISSUE THREAD

**Issue by foobarbecue** [toofusan/Twity#7]
Readme has links to https://dev.twity.com/ . The SSL cert is wrong and even if you ignore that, the server just returns 400 for all pages.

**Comment by toofusan** [comment]
I have to say that dev.twity.com is NOT my website. I don't have any other website about this library than GitHub. Where this url comes from?

**Comment by foobarbecue** [comment]
It's on your README.md . Possibly a find and replace mistake?

**Comment by foobarbecue** [comment]
Oh, I see now. It's supposed to be dev.twitter.com -- a link to Twitter's documentation.

**Comment by toofusan** [comment]
Ah..., I had not realized broken links. sorry...
I'll check your pull request soon, thank you.
